import os
import logging
from git import Repo, Actor
from pathlib import Path

logger = logging.getLogger(__name__)

class GitManager:
    def __init__(self, repo_path: Path):
        self.repo_path = repo_path
        self.repo = None
        self._init_repo()

    def _init_repo(self):
        if not self.repo_path.exists():
            self.repo_path.mkdir(parents=True, exist_ok=True)
        
        if (self.repo_path / '.git').exists():
            self.repo = Repo(self.repo_path)
        else:
            # Yeni bir repo başlat
            logger.info(f'Initializing new repo at {self.repo_path}')
            self.repo = Repo.init(self.repo_path)
            
            # Config ayarla (Ajan kimliği)
            with self.repo.config_writer() as git_config:
                git_config.set_value('user', 'name', 'Multi-AI Agent')
                git_config.set_value('user', 'email', 'agent@ai.local')
            
            # --- FIX: INITIAL COMMIT ---
            # Branch açabilmek için en az 1 commit olmalı.
            readme = self.repo_path / 'README.md'
            if not readme.exists():
                readme.write_text('# Multi-AI Workspace\nGenerated by AI Agent.', encoding='utf-8')
            
            self.repo.git.add(A=True)
            self.repo.index.commit('Initial commit by System')
            logger.info('✅ Created Initial Commit (HEAD established)')

    def checkout_branch(self, branch_name: str):
        # Branch yoksa oluştur, varsa geç
        # HEAD hatası almamak için create_head öncesi repo durumunu kontrol ediyoruz
        if branch_name in self.repo.heads:
            self.repo.heads[branch_name].checkout()
            logger.info(f'Switched to existing branch: {branch_name}')
        else:
            self.repo.create_head(branch_name).checkout()
            logger.info(f'Created and switched to new branch: {branch_name}')

    def commit_all(self, message: str):
        if not self.repo.is_dirty(untracked_files=True):
            logger.info('No changes to commit.')
            return
            
        self.repo.git.add(A=True)
        self.repo.index.commit(message)
        logger.info(f'Committed changes: {message}')

    def push(self, remote_name='origin', branch_name='main'):
        # Dry-run log
        logger.info(f'Pushing to {remote_name}/{branch_name}...')
